name: iOS Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test HomeBrewAssistant
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        
    - name: Cache Build Products
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/.swiftpm
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.swift', '**/*.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
        
    - name: List Available Simulators
      run: |
        echo "Available iOS Simulators:"
        xcrun simctl list devices iOS available
        
    - name: Select iOS Simulator
      run: |
        SIMULATOR=$(xcrun simctl list devices iOS available | grep "iPhone" | head -1 | sed 's/.*(\([^)]*\)).*/\1/')
        echo "Using simulator: $SIMULATOR"
        echo "SIMULATOR_ID=$SIMULATOR" >> $GITHUB_ENV
        
    - name: Build Project
      run: |
        set -o pipefail
        xcodebuild clean build \
          -project HomeBrewAssistant.xcodeproj \
          -scheme HomeBrewAssistant \
          -destination 'platform=iOS Simulator,id=${{ env.SIMULATOR_ID }}' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          ARCHS=arm64 \
          ONLY_ACTIVE_ARCH=YES \
          | tee build.log
          
    - name: Run Tests
      run: |
        set -o pipefail
        xcodebuild test \
          -project HomeBrewAssistant.xcodeproj \
          -scheme HomeBrewAssistant \
          -destination 'platform=iOS Simulator,id=${{ env.SIMULATOR_ID }}' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          ARCHS=arm64 \
          ONLY_ACTIVE_ARCH=YES \
          | tee test.log || echo "Tests completed (some may have failed)"
          
    - name: Upload Build Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          build.log
          test.log
          
    - name: Build Status
      run: |
        echo "✅ Build completed successfully!"
        echo "Repository: HomeBrewAssistant"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}" 